### ISSUE TITLE
Align Consent form to our Design System

### ISSUE THREAD

**Issue by ritapatel7** [barnardos/consent-form-builder-rails#229]
_As a developer
I want to make sure the Consent form aligns with our Design System
So that our Design guidelines are followed for this project_ 

# Acceptance criteria
- [ ] Compare consent form to design system
- [ ] List changes that need to be made
- [ ] Implement the changes

**Comment by jeddy3** [comment]
> Compare consent form to design system

At the moment I believe the following areas of guidance are applicable to the content form builder:

- consistent typography
- consistent spacing
- proportional scaling approach for optimal line length and spacing across viewport sizes
- requesting and submitting i.e. forms.

I believe each of these can be applied independently. As such, this issue can be broken down into smaller tasks.

**Comment by ritapatel7** [comment]
In addition to Richard's areas above

- Update colours on buttons 
- Update font to large text on buttons 
- Main content area size different to digi tran. Best to keep one size for main content across apps? Unless specific size required

**Comment by sampling** [comment]
The separate cards were created for actions listed here. Closing
